apiVersion: v2
appVersion: "2.4.11"
description: >
  Helm chart to deploy Open5gs sepp service on Kubernetes.
home: https://github.com/gradiant/openverso-charts
sources:
  - http://open5gs.org
icon: https://open5gs.org/assets/img/open5gs-logo.png
maintainers:
- email: cgiraldo@gradiant.org
  name: cgiraldo
name: open5gs-sepp
version: 2.1.0
keywords:
  - epc
  - ngc
  - sepp
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
