{{ $open5gsName := .Release.Name }}
logger:
  level: {{ .Values.config.logLevel }}
parameter: {}

sbi:
  server:
    no_tls: {{ .Values.config.sbi.server.no_tls }}
  client:
    no_tls: {{ .Values.config.sbi.client.no_tls }}

udm:
  sbi:
    - address: udm.5gc.mnc0{{ .Values.global.mnc }}.mcc{{ .Values.global.mcc }}.3gppnetwork.org
      {{- if .Values.config.sbi.advertise }}
      advertise: "{{ tpl .Values.config.sbi.advertise . }}"
      {{- end }}

{{- if .Values.config.nrf.enabled }}
  nrf:
    - uri: http://{{ default (printf "%s-nrf-sbi" $open5gsName) .Values.config.nrf.sbi.hostname }}:{{ .Values.config.nrf.sbi.port }}
{{- end }}

{{- if .Values.config.scp.enabled }}
  scp:
    - uri: http://{{ default (printf "%s-scp-sbi" $open5gsName) .Values.config.scp.sbi.hostname }}:{{ .Values.config.scp.sbi.port }}
{{- end }}
