{{ $open5gsName := .Release.Name }}
logger:
  level: {{ .Values.config.logLevel }}
parameter: {}

sbi:
  server:
    no_tls: {{ .Values.config.sbi.server.no_tls }}
  client:
    no_tls: {{ .Values.config.sbi.client.no_tls }}

scp:
  defconfig:
    tls:
      client:
        schema: http
  sbi:
    - dev: "eth0"
      port: {{ .Values.containerPorts.sbi }}
  nrf:
    - uri: http://{{ default (printf "%s-nrf-sbi" $open5gsName) .Values.config.nrf.sbi.hostname }}:{{ .Values.config.nrf.sbi.port }}
