dbURI: "mongodb://{{ .Release.Name }}-mongodb/open5gs"

populate:
  enabled: true
  image:
    registry: docker.io
    repository: openverso/open5gs-dbctl
    tag: 0.10.2
    pullPolicy: IfNotPresent
  initCommands: []
  # example of initCommands:
  #  - open5gs-dbctl add 999700000000001 465B5CE8B199B49FAA5F0A2EE238A6BC E8ED289DEBA952E4283B54E88E6183CA
  #  - open5gs-dbctl add_ue_with_apn 999700000000002 465B5CE8B199B49FAA5F0A2EE238A6BC E8ED289DEBA952E4283B54E88E6183CA internet
  #  - open5gs-dbctl add_ue_with_slice 999700000000003 465B5CE8B199B49FAA5F0A2EE238A6BC E8ED289DEBA952E4283B54E88E6183CA internet 1 111111

# Common
mongodb:
  enabled: true
  auth:
    enabled: false
smf:
  enabled: false
  image:
    repository: haoli1/open5gs-roaming
    tag: latest
upf:
  enabled: false
  image:
    repository: haoli1/open5gs-roaming
    tag: latest
webui:
  enabled: true
  image:
    tag: 2.6.4

# 4G
hss:
  enabled: false
  image:
    repository: haoli1/open5gs-roaming
    tag: latest
  mongodb:
    enabled: false
mme:
  enabled: false
  image:
    repository: haoli1/open5gs-roaming
    tag: latest
pcrf:
  enabled: false
  image:
    repository: haoli1/open5gs-roaming
    tag: latest
  mongodb:
    enabled: false
sgwc:
  enabled: false
  image:
    repository: haoli1/open5gs-roaming
    tag: latest
sgwu:
  enabled: false
  image:
    repository: haoli1/open5gs-roaming
    tag: latest

# 5G
amf:
  enabled: true
  image:
    repository: haoli1/open5gs-roaming
    tag: latest
ausf:
  enabled: false
  image:
    repository: haoli1/open5gs-roaming
    tag: latest
bsf:
  enabled: false
  image:
    repository: haoli1/open5gs-roaming
    tag: latest
nrf:
  enabled: true
  image:
    repository: haoli1/open5gs-roaming
    tag: latest
nssf:
  enabled: false
  image:
    repository: haoli1/open5gs-roaming
    tag: latest
pcf:
  enabled: false
  image:
    repository: haoli1/open5gs-roaming
    tag: latest
  mongodb:
    enabled: false
udm:
  enabled: true
  image:
    repository: haoli1/open5gs-roaming
    tag: latest
udr:
  enabled: true
  image:
    repository: haoli1/open5gs-roaming
    tag: latest
  mongodb:
    enabled: false
scp:
  enabled: true
  image:
    repository: haoli1/open5gs-roaming
    tag: latest
  mongodb:
    enabled: false
sepp:
  enabled: true
  image:
    repository: haoli1/open5gs-roaming
    tag: latest
  mongodb:
    enabled: false
