{{ $open5gsName := .Release.Name }}
{{ $peer5gsName := required "A valid peer name is required" .Values.config.peer }}
logger:
  level: {{ .Values.config.logLevel }}
parameter: {}

sbi:
  server:
    no_tls: {{ .Values.config.sbi.server.no_tls }}
  client:
    no_tls: {{ .Values.config.sbi.client.no_tls }}

sepp:
  sbi:
    - address: {{ (printf "%s-sepp-sbi" $open5gsName) }}
      port: {{ .Values.containerPorts.sbi }}
{{- if .Values.config.nrf.enabled }}
  nrf:
    - uri: http://{{ default (printf "%s-nrf-sbi" $open5gsName) .Values.config.nrf.sbi.hostname }}:{{ .Values.config.nrf.sbi.port }}
{{- end }}
{{- if .Values.config.scp.enabled }}
  scp:
    - uri: http://{{ default (printf "%s-scp-sbi" $open5gsName) .Values.config.scp.sbi.hostname }}:{{ .Values.config.scp.sbi.port }}
{{- end }}
  sepp:
    uri: http://{{ (printf "%s-sepp-sbi" $peer5gsName) }}:{{ .Values.containerPorts.sbi }}
